title: Rafael Urben
description: Dokumentationen zu meinen Projekten
url: https://www.rafaelurben.ch
plugins:
  - jekyll-last-modified
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      last-modified-at: 2021-01-27 18:30:00 +0100