title: Rafael Urben
description: Dokumentationen zu meinen Projekten
url: https://www.rafaelurben.ch
plugins:
  - jekyll-last-modified
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      last-modified-at: 2021-02-04 12:30:00 +0100
  - 
    scope:
      path: "de/projects/minecraft"
    values:
      titlebg: "#0a9029"
  - 
    scope:
      path: "en/projects/minecraft"
    values:
      titlebg: "#0a9029"
  - 
    scope:
      path: "en"
    values:
      language: en