title: Rafael Urben
description: Rafaels Portfolio-Webseite
url: https://www.rafaelurben.ch
repository: rafaelurben/rafaelurben.github.io
plugins:
  - jekyll-last-modified
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      last_modified_at: 2025-09-08 03:14:16 +0100
  -
    scope:
      path: "redirects"
      type: "pages"
    values:
      layout: redirect
      noindex: true
      sitemap: false
exclude:
  - README.md
  - LICENSE
  - CNAME
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
