categories:
  web:
    title: Web
  tools:
    title: Apps & Tools
  gameextensions:
    title: Spielerweiterungen
  uncategorized:
    title: Unkategorisiert
project_status:
  finished:
    title: Abgeschlossen
    description: Das Projekt wurde fertiggestellt und funktioniert wie geplant.
    bg-color: darkgreen
    fg-color: white
  stable:
    title: Stabil
    description: Das Projekt ist stabil und funktioniert gut.
    bg-color: "#008a00"
    fg-color: white
  beta:
    title: Beta
    description: Das Projekt ist noch instabil aber hat bereits einen Grossteil der geplanten Funktionen.
    bg-color: yellow
    fg-color: black
  alpha:
    title: Alpha
    description: Das Projekt ist noch instabil und hat erste wenige Funktionen.
    bg-color: orange
    fg-color: white
  dev:
    title: In Entwicklung
    description: Das Projekt ist noch in der Entwicklungsphase und ist noch nicht brauchbar.
    bg-color: red
    fg-color: white
  outdated:
    title: Veraltet
    description: Das Projekt ist veraltet.
    bg-color: darkred
    fg-color: white
dev_status:
  ended:
    title: Beendet
    description: Die Entwicklung wurde beendet.
    bg-color: "#446CCF"
    fg-color: white
  active:
    title: Aktiv
    description: Das Projekt wird aktiv weiterentwickelt.
    bg-color: "#0AFFFF"
    fg-color: black
  passive:
    title: Passiv
    description: Das Projekt wird passiv weiterentwickelt.
    bg-color: "#6BCAE2"
    fg-color: black
  paused:
    title: Pausiert
    description: Das Projekt ist pausiert und wird derzeit nicht weiterentwickelt.
    bg-color: "#C6E6FB"
    fg-color: black
  abandoned:
    title: Aufgegeben
    description: Das Projekt wurde aufgegeben/vernachlässigt.
    bg-color: "#000080"
    fg-color: white
